# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ed422231a2544d8a8bb1f1833df9ddd8a7d032052acfea2fd067f713d982a0a8e93874cde7494f2d2f6bb7edeb858dfe13cdf7e8dc79376c27a931bc6a93f6f

test:
  secret_key_base: c089f1fa7d580fb868516589b8b55172bdcd5b0a625fd68ae8d8e55b59bb36571358deb2f7535b8ffab02fd8d9624431e818ba3a3ac7951a31caed271d163c86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
